#!/bin/sh
#
#  Test cmd execution 
#  - command returns with the status given with the -e option
#
instdir=$(cd $(dirname $0); pwd)
touch ${instdir}/log.sh


. ${instdir}/log.sh
log_init $0
#
usage()
{
    echo "Test [-e {status}]"
}

exitStatus=0

O=`getopt he: "$@"` || exit 1
eval set -- "$O"

while getopts "he:" arg ; do
    case $arg in 
        h)
            usage
            exit 0
            ;;
        e)
            exitStatus="$2"
            ;;
        *)
            log "[E] unknown arg:  $arg"
            exit 1
            ;;
    esac
done

if [ $exitStatus -ne 0 ]; then
  log "[E] Test status $exitStatus"
else 
  log "$0 success"
fi

exit "$exitStatus"
